/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/posts/5分钟实现一键文本识别工具': RouteRecordInfo<'/posts/5分钟实现一键文本识别工具', '/posts/5分钟实现一键文本识别工具', Record<never, never>, Record<never, never>>,
    '/posts/GitLab-CI-搭建指南': RouteRecordInfo<'/posts/GitLab-CI-搭建指南', '/posts/GitLab-CI-搭建指南', Record<never, never>, Record<never, never>>,
    '/posts/macOS配置mongoDB支持事务': RouteRecordInfo<'/posts/macOS配置mongoDB支持事务', '/posts/macOS配置mongoDB支持事务', Record<never, never>, Record<never, never>>,
    '/posts/一次线上事故 Case Study': RouteRecordInfo<'/posts/一次线上事故 Case Study', '/posts/一次线上事故 Case Study', Record<never, never>, Record<never, never>>,
    '/posts/关于读博这件事': RouteRecordInfo<'/posts/关于读博这件事', '/posts/关于读博这件事', Record<never, never>, Record<never, never>>,
    '/posts/创建hexo脚本': RouteRecordInfo<'/posts/创建hexo脚本', '/posts/创建hexo脚本', Record<never, never>, Record<never, never>>,
    '/posts/如何实现复制Excel内容更新数据': RouteRecordInfo<'/posts/如何实现复制Excel内容更新数据', '/posts/如何实现复制Excel内容更新数据', Record<never, never>, Record<never, never>>,
    '/posts/学以致用': RouteRecordInfo<'/posts/学以致用', '/posts/学以致用', Record<never, never>, Record<never, never>>,
    '/posts/导出微信聊天记录': RouteRecordInfo<'/posts/导出微信聊天记录', '/posts/导出微信聊天记录', Record<never, never>, Record<never, never>>,
    '/posts/微信逃离指南': RouteRecordInfo<'/posts/微信逃离指南', '/posts/微信逃离指南', Record<never, never>, Record<never, never>>,
    '/posts/爬取微信公众号文章': RouteRecordInfo<'/posts/爬取微信公众号文章', '/posts/爬取微信公众号文章', Record<never, never>, Record<never, never>>,
    '/posts/规则配置平台': RouteRecordInfo<'/posts/规则配置平台', '/posts/规则配置平台', Record<never, never>, Record<never, never>>,
    '/posts/解决国内-OpenStreetMap-地图无法显示的问题': RouteRecordInfo<'/posts/解决国内-OpenStreetMap-地图无法显示的问题', '/posts/解决国内-OpenStreetMap-地图无法显示的问题', Record<never, never>, Record<never, never>>,
    '/posts/远程访问WSL': RouteRecordInfo<'/posts/远程访问WSL', '/posts/远程访问WSL', Record<never, never>, Record<never, never>>,
    '/posts/部署-FRP-反向代理流程': RouteRecordInfo<'/posts/部署-FRP-反向代理流程', '/posts/部署-FRP-反向代理流程', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-starter@0.3.1/node_modules/valaxy-theme-starter/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@vue+compiler-dom@3.5.20_@vue+co_dxmrspqwrb4z647p7gpg6tjv4q/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'pages/posts/5分钟实现一键文本识别工具.md': {
      routes: '/posts/5分钟实现一键文本识别工具'
      views: never
    }
    'pages/posts/GitLab-CI-搭建指南.md': {
      routes: '/posts/GitLab-CI-搭建指南'
      views: never
    }
    'pages/posts/macOS配置mongoDB支持事务.md': {
      routes: '/posts/macOS配置mongoDB支持事务'
      views: never
    }
    'pages/posts/一次线上事故 Case Study.md': {
      routes: '/posts/一次线上事故 Case Study'
      views: never
    }
    'pages/posts/关于读博这件事.md': {
      routes: '/posts/关于读博这件事'
      views: never
    }
    'pages/posts/创建hexo脚本.md': {
      routes: '/posts/创建hexo脚本'
      views: never
    }
    'pages/posts/如何实现复制Excel内容更新数据.md': {
      routes: '/posts/如何实现复制Excel内容更新数据'
      views: never
    }
    'pages/posts/学以致用.md': {
      routes: '/posts/学以致用'
      views: never
    }
    'pages/posts/导出微信聊天记录.md': {
      routes: '/posts/导出微信聊天记录'
      views: never
    }
    'pages/posts/微信逃离指南.md': {
      routes: '/posts/微信逃离指南'
      views: never
    }
    'pages/posts/爬取微信公众号文章.md': {
      routes: '/posts/爬取微信公众号文章'
      views: never
    }
    'pages/posts/规则配置平台.md': {
      routes: '/posts/规则配置平台'
      views: never
    }
    'pages/posts/解决国内-OpenStreetMap-地图无法显示的问题.md': {
      routes: '/posts/解决国内-OpenStreetMap-地图无法显示的问题'
      views: never
    }
    'pages/posts/远程访问WSL.md': {
      routes: '/posts/远程访问WSL'
      views: never
    }
    'pages/posts/部署-FRP-反向代理流程.md': {
      routes: '/posts/部署-FRP-反向代理流程'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
