/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/a_production_env_accident_Case_Study': RouteRecordInfo<
      '/posts/a_production_env_accident_Case_Study',
      '/posts/a_production_env_accident_Case_Study',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai_tool_and_recent_develop_plan': RouteRecordInfo<
      '/posts/ai_tool_and_recent_develop_plan',
      '/posts/ai_tool_and_recent_develop_plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/all_about_doctor_degree': RouteRecordInfo<
      '/posts/all_about_doctor_degree',
      '/posts/all_about_doctor_degree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/copy_excel_to_update_data': RouteRecordInfo<
      '/posts/copy_excel_to_update_data',
      '/posts/copy_excel_to_update_data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/create_hexo_bash': RouteRecordInfo<
      '/posts/create_hexo_bash',
      '/posts/create_hexo_bash',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/deploy-FRP': RouteRecordInfo<
      '/posts/deploy-FRP',
      '/posts/deploy-FRP',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/escape_from_wechat': RouteRecordInfo<
      '/posts/escape_from_wechat',
      '/posts/escape_from_wechat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/export_wechat_chat_history': RouteRecordInfo<
      '/posts/export_wechat_chat_history',
      '/posts/export_wechat_chat_history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GitLab-CI-build_guide': RouteRecordInfo<
      '/posts/GitLab-CI-build_guide',
      '/posts/GitLab-CI-build_guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/learn_to_use': RouteRecordInfo<
      '/posts/learn_to_use',
      '/posts/learn_to_use',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/macOS_config_mongoDB_transaction': RouteRecordInfo<
      '/posts/macOS_config_mongoDB_transaction',
      '/posts/macOS_config_mongoDB_transaction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/OCR-tool': RouteRecordInfo<
      '/posts/OCR-tool',
      '/posts/OCR-tool',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/remote_access_WSL': RouteRecordInfo<
      '/posts/remote_access_WSL',
      '/posts/remote_access_WSL',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/rule_config_platform': RouteRecordInfo<
      '/posts/rule_config_platform',
      '/posts/rule_config_platform',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/solve_mainland_OpenStreetMap_issue': RouteRecordInfo<
      '/posts/solve_mainland_OpenStreetMap_issue',
      '/posts/solve_mainland_OpenStreetMap_issue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/spider_wechat_official_accont_posts': RouteRecordInfo<
      '/posts/spider_wechat_official_accont_posts',
      '/posts/spider_wechat_official_accont_posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-starter/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'pages/posts/a_production_env_accident_Case_Study.md': {
      routes:
        | '/posts/a_production_env_accident_Case_Study'
      views:
        | never
    }
    'pages/posts/ai_tool_and_recent_develop_plan.md': {
      routes:
        | '/posts/ai_tool_and_recent_develop_plan'
      views:
        | never
    }
    'pages/posts/all_about_doctor_degree.md': {
      routes:
        | '/posts/all_about_doctor_degree'
      views:
        | never
    }
    'pages/posts/copy_excel_to_update_data.md': {
      routes:
        | '/posts/copy_excel_to_update_data'
      views:
        | never
    }
    'pages/posts/create_hexo_bash.md': {
      routes:
        | '/posts/create_hexo_bash'
      views:
        | never
    }
    'pages/posts/deploy-FRP.md': {
      routes:
        | '/posts/deploy-FRP'
      views:
        | never
    }
    'pages/posts/escape_from_wechat.md': {
      routes:
        | '/posts/escape_from_wechat'
      views:
        | never
    }
    'pages/posts/export_wechat_chat_history.md': {
      routes:
        | '/posts/export_wechat_chat_history'
      views:
        | never
    }
    'pages/posts/GitLab-CI-build_guide.md': {
      routes:
        | '/posts/GitLab-CI-build_guide'
      views:
        | never
    }
    'pages/posts/learn_to_use.md': {
      routes:
        | '/posts/learn_to_use'
      views:
        | never
    }
    'pages/posts/macOS_config_mongoDB_transaction.md': {
      routes:
        | '/posts/macOS_config_mongoDB_transaction'
      views:
        | never
    }
    'pages/posts/OCR-tool.md': {
      routes:
        | '/posts/OCR-tool'
      views:
        | never
    }
    'pages/posts/remote_access_WSL.md': {
      routes:
        | '/posts/remote_access_WSL'
      views:
        | never
    }
    'pages/posts/rule_config_platform.md': {
      routes:
        | '/posts/rule_config_platform'
      views:
        | never
    }
    'pages/posts/solve_mainland_OpenStreetMap_issue.md': {
      routes:
        | '/posts/solve_mainland_OpenStreetMap_issue'
      views:
        | never
    }
    'pages/posts/spider_wechat_official_accont_posts.md': {
      routes:
        | '/posts/spider_wechat_official_accont_posts'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
