/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/posts/5分钟实现一键文本识别工具': RouteRecordInfo<'/posts/5分钟实现一键文本识别工具', '/posts/5分钟实现一键文本识别工具', Record<never, never>, Record<never, never>>,
    '/posts/部署-FRP-反向代理流程': RouteRecordInfo<'/posts/部署-FRP-反向代理流程', '/posts/部署-FRP-反向代理流程', Record<never, never>, Record<never, never>>,
    '/posts/创建hexo脚本': RouteRecordInfo<'/posts/创建hexo脚本', '/posts/创建hexo脚本', Record<never, never>, Record<never, never>>,
    '/posts/导出微信聊天记录': RouteRecordInfo<'/posts/导出微信聊天记录', '/posts/导出微信聊天记录', Record<never, never>, Record<never, never>>,
    '/posts/关于读博这件事': RouteRecordInfo<'/posts/关于读博这件事', '/posts/关于读博这件事', Record<never, never>, Record<never, never>>,
    '/posts/规则配置平台': RouteRecordInfo<'/posts/规则配置平台', '/posts/规则配置平台', Record<never, never>, Record<never, never>>,
    '/posts/解决国内-OpenStreetMap-地图无法显示的问题': RouteRecordInfo<'/posts/解决国内-OpenStreetMap-地图无法显示的问题', '/posts/解决国内-OpenStreetMap-地图无法显示的问题', Record<never, never>, Record<never, never>>,
    '/posts/爬取微信公众号文章': RouteRecordInfo<'/posts/爬取微信公众号文章', '/posts/爬取微信公众号文章', Record<never, never>, Record<never, never>>,
    '/posts/如何实现复制Excel内容更新数据': RouteRecordInfo<'/posts/如何实现复制Excel内容更新数据', '/posts/如何实现复制Excel内容更新数据', Record<never, never>, Record<never, never>>,
    '/posts/微信逃离指南': RouteRecordInfo<'/posts/微信逃离指南', '/posts/微信逃离指南', Record<never, never>, Record<never, never>>,
    '/posts/学以致用': RouteRecordInfo<'/posts/学以致用', '/posts/学以致用', Record<never, never>, Record<never, never>>,
    '/posts/一次线上事故 Case Study': RouteRecordInfo<'/posts/一次线上事故 Case Study', '/posts/一次线上事故 Case Study', Record<never, never>, Record<never, never>>,
    '/posts/远程访问WSL': RouteRecordInfo<'/posts/远程访问WSL', '/posts/远程访问WSL', Record<never, never>, Record<never, never>>,
    '/posts/GitLab-CI-搭建指南': RouteRecordInfo<'/posts/GitLab-CI-搭建指南', '/posts/GitLab-CI-搭建指南', Record<never, never>, Record<never, never>>,
    '/posts/macOS配置mongoDB支持事务': RouteRecordInfo<'/posts/macOS配置mongoDB支持事务', '/posts/macOS配置mongoDB支持事务', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
